### ISSUE TITLE
Lack Of Example

### ISSUE THREAD

**Issue by ayushchadha23** [dukke/parallax-list-view#1]
I need to use this wonderful library for my app but I desperately need a example for fxml can you pls share the fxml and document controller code?

**Comment by dukke** [comment]
At the end of the documentation page: https://www.pixelduke.com/fxparallax Will see it says that the test folder inside the repo has a couple of examples.

Are you still having trouble finding examples? Can you tell me what you don't understand exactly?

Thanks!

**Comment by ayushchadha23** [comment]
@dukke thanks ! It helped me !

**Comment by dukke** [comment]
I wonder why didn't you find this before? Is this information not clearly visible?
