### ISSUE TITLE
Make parallax pane scenebuilder friendly!

### ISSUE THREAD

**Issue by ayushchadha23** [dukke/parallax-list-view#2]
This is an awesome library! But I am interested to use this in scenebuilder, this would build some awesome UI! It would be appreciated if you did. I don't know but scenebuilder crashes when I drag parallax pane into my scene.

**Comment by dukke** [comment]
Hi!

Are you able to see what exception is thrown?

Thanks,

**Comment by dukke** [comment]
I suspect this could be more of a Scene Builder issue than an issue with this library, since all sample code is created through FXML.

**Comment by ayushchadha23** [comment]
No,i am not able to see what exception is thrown

**Comment by ayushchadha23** [comment]
it's strange about scenebuilder

**Comment by dukke** [comment]
Maybe file the issue on Scene Builder and see what they say...?
